#!/usr/bin/env bash
#this program prints Best School to 10
#when it reaches 9 it prints Best School and hi

for ((num = 1; num <=10; num++))
do
	echo "Best School"
	if ((num == 9)); then
		echo "Hi"
	fi
done
