#!/usr/bin/env bash
#prints numbers from 1 to 20 usin a while loop
#displays 4 and then bad luck from China for the 4th loop iteration
#displays 9 and then bad luck from Japan for the 9th loop iteration
#displays 17 and then bad luck from Italy for the 17th loop iteration

counter=1

while [ $counter -le 20 ]
do
	if ((counter == 4)); then
		echo $counter
		echo "bad luckfrom China"
	elif ((counter == 9)); then
		echo $counter
		echo "bad luck from Japan"
	elif ((counter == 17)); then
		echo $counter
		echo "bad luck from Italy"
	else
		echo $counter
	fi
	((counter++))
done
